import { OnInit } from '@angular/core';
import * as moment_ from 'moment';
import { CalendarDay } from '../types';
export declare class SgvCalendarComponent implements OnInit {
    private locale;
    defaults: any;
    weeks: Array<Array<CalendarDay>>;
    side: string;
    headings: string[];
    private period;
    private events;
    private year;
    private month;
    private monthIndex;
    private firstMonday;
    private hoveredDate;
    constructor(locale: string, defaults: any);
    ngOnInit(): void;
    getMonthTitle(): string;
    navigate(direction: string): void;
    select(day: CalendarDay): void;
    onHover(day: CalendarDay): void;
    isSelected(date: moment_.Moment): boolean;
    isBetween(date: moment_.Moment): boolean;
    private init;
    private buildCalendar;
    private buildWeek;
    private incMonth;
    private decMonth;
}
